</td> 
 <td width="170"> 
  <center>  
  <?php include("googleads.inc"); ?> 
  </center> 
 </td> 
  </tr> 
</table> 


<p align="center"><br> 
<img height="2" src="line.gif" width="730" border="0"><br> 
<strong><font color="#000000" face="Comic Sans MS">TheDemoSite.co.uk</font></strong> is a 
MySQL database and PHP FREE code example site hosted with: <br> 
<strong><a href="https://www.seiretto.co.uk/">UK hosting and DNS management for AC.UK and GOV.UK domain names - Seiretto Ltd</a></strong> 
Copyright © 1996-2015.&nbsp; All rights reserved. 
</p> 
<p align="center">sample code:&nbsp;<a href="http://asp.thedemosite.co.uk/">ASP and MySQL</a>  
    - <a href="http://php.thedemosite.co.uk/">PHP and MySQL</a> 


- <a href="http://thedemosite.co.uk/phpformmailer/">phpFormMailer</a> - 
<a href="http://asp.thedemosite.co.uk/asp_contact_email_form/asp_contact_email_form.asp"> 
ASP Contact form</a><br><img height="2" src="line.gif" width="730" border="0"></p> 
</body> 
</html> 