<?php 
if (!isset($page_title)) $page_title="PHP code and online MySQL database - example username password"; 
if (!isset($page_keywords)) $page_keywords="free PHP code, mysql sql"; 
if (!isset($page_desc)) $page_desc="FREE example PHP code and a MySQL database"; 
?> 
<html> 

<head> 
<title><?php echo $page_title; ?></title> 
<meta NAME="keywords" CONTENT="<?php echo $page_keywords; ?>"> 
<meta NAME="description" CONTENT="<?php echo $page_desc; ?>"> 
<meta NAME="Content-Language" CONTENT="english"> 
<meta name="Revisit-after" content="56 days"> 
<meta name="Distribution" content="Global"> 
<meta name="Copyright" content="Copyright © 1996-2008 Seiretto.com"> 
<meta NAME="ROBOTS" CONTENT="ALL"> 
<link rel="stylesheet" type="text/css" href="tds.css"> 
<style type="text/css"> 
.auto-style1 { 
    text-align: center; 
} 
</style> 
</head> 

<body BACKGROUND="DiscoverBack.gif" 
style=" 
    SCROLLBAR-ARROW-COLOR: #BBCCFF;  
    SCROLLBAR-TRACK-COLOR: #C9DAF7;  
    SCROLLBAR-FACE-COLOR:  #002163;" 
TOPMARGIN="0" LEFTMARGIN="15" MARGINWIDTH="0" MARGINHEIGHT="0"> 
<div align="center"><center> 

<strong><font color="#000000" face="Comic Sans MS">TheDemoSite.co.uk</font></strong>&nbsp;  
    sample code:&nbsp;<a href="http://asp.thedemosite.co.uk/">ASP and MySQL</a>  
    - <a href="http://php.thedemosite.co.uk/">PHP and MySQL</a> 
    - <a href="http://thedemosite.co.uk/phpformmailer/">phpFormMailer</a> - 
    <a href="http://asp.thedemosite.co.uk/asp_contact_email_form/asp_contact_email_form.asp"> 
    ASP Contact form</a>&nbsp;&nbsp; 
<table border="0" width="100%" cellspacing="0" cellpadding="0"> 
  <tr> 
    <td width="100%"><p align="center"><img height="2" src="line.gif" width="99%" border="0" 
    alt="PHP code examples with database connectivity"></td> 
  </tr> 
  <tr> 
    <td width="100%"><img height="2" src="line.gif" width="99%" border="0" 
    alt="PHP code examples with database connectivity"><div align="center"><center><table 
    border="0" width="98%" cellspacing="0" cellpadding="0"> 
      <tr> 
        <td style="width: 22%"><font face="Comic Sans MS"><big><strong>PHP and  
        MySQL<br></strong>sample code</big></font></td> 
        <td><p align="center"><small>Just examples of <b>PHP</b> code, linking to your <b>MySQL</b> 
        database and JavaScript.<br> 
        <a href="index.php">1. Home</a> | <a href="thedatabase.php">2. The Database</a> | <a 
        href="addauser.php">3. Add a User</a> | <a href="login.php">4. Login</a> | <a 
        href="getyourowndbonline.php">5. Get your db online</a></small></td> 
      </tr> 
    </table> 
    </center></div></td> 
  </tr> 
  <tr> 
    <td width="100%"><p align="center"><img height="2" src="line.gif" width="99%" border="0" 
    alt="PHP code examples with database connectivity"><br> 
    </td> 
  </tr> 
</table> 
</center></div> 

<table border="0" width="100%"> 
  <tr> 
    <td class="auto-style1"> 
    <div style="font-style:italic; color:green">All code updated April 2014, now uses PHP/PDO for database connectivity</div> 
